### PR TITLE
Update project layout

### PR DESCRIPTION
**Pull request by oschulz**
Updates Project.toml and Tavis/Appveyor CI, removes "REQUIRES" files.

Should make PiCraft ready for Registrator.

I'm not sure how docs generation is supposed to work, which Minecraft server is it supposed to connect to?

### CODE REVIEW

**Comment by aviks** [comment]
Sorry, I missed this PR completely. Aplogies, and thanks. 

If you're still interested in pursuing this (and I fully understand if not) I generally prefer not to have `Manifest.toml` checked in. 

>I'm not sure how docs generation is supposed to work, which Minecraft server is it supposed to connect to?

Yes, this is a problem, since Minecraft if paid software (or limited to specific hardware if free). Doc generation should be possible wihout a connection (obviously not running any doctests or live output) but the pacakge needs to load in disconnected mode at least.

**Comment by Ellipse0934** [comment]
To me CI does not make sense in the context of this package.

> I generally prefer not to have Manifest.toml checked in
I'm sorry I didn't understand what this means, isn't manifest generated automatically ? 

I was going to merge my branch which takes care of the LinearAlgebra deps [here](https://github.com/JuliaBerry/PiCraft.jl/compare/master...Ellipse0934:newreadme) . Should I merge it ?

**Comment by aviks** [comment]
> I'm sorry I didn't understand what this means, isn't manifest generated automatically ?

Yes, it's generated automatically, and thus should not be checked into git. This PR adds manifest.toml to git. 

> Should I merge it ?

Yes, let's do that.

**Comment by oschulz** [comment]
Thanks! I'll close this one, then, right?

**Comment by oschulz** [comment]
> Sorry, I missed this PR completely. Aplogies, and thanks.

No worries!

**Comment by oschulz** [comment]
Off topic - I wish there was a way to couple this with Bedrock Edition ...

**Pull request closed without merging**
